name: Publish package to PyPi

on:
  # This allows you to manually run the workflow from the GitHub Actions tab.
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to build from (e.g., main or v1.0.0)'
        required: true
        default: 'main'
      release_title:
        description: 'Release Title (e.g., v1.0.0: Initial Release)'
        required: true # Making title required for a proper release
      # Removed release_notes input here

jobs:
  push:
    runs-on: ubuntu-latest

    # UPDATED: Permissions now include 'releases: write'
    permissions:
      id-token: write
      contents: read
      releases: write # <-- REQUIRED for creating the GitHub Release

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11 

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      # 2. Publish to PyPi (using Trusted Publisher)
      - name: Publish to PyPi (using Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1

      # 3. ADDED: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.branch }} 
          release_name: ${{ github.event.inputs.release_title }}
          # The body now uses the title since release_notes was removed
          body: ${{ github.event.inputs.release_title }}
          draft: false
          prerelease: false
